title: Ganesan Santhanam
author: Ganesan Santhanam
url: https://ganesh96.github.io/ganesan-santhanam.github.io/
description: >
  Full Stack Software Engineer with 5 years of experience building scalable, cloud-native applications with creative and sophisticated approaches such as Event-Driven Design, Microservice Architecture, and AI/ML.
permalink: /:slug
favicon: "./logo.png"

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%d-%m-%Y"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: true
  show_old_projects: false
  show_misc_list: true
  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Old Projects

soopr:
  publish_token: ""

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag